<?php

/**
 * @file
 * Contains owp_employee_engagement.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 * @param $route_name
 * @param RouteMatchInterface $route_match
 * @return string
 */
function owp_employee_engagement_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the owp_employee_engagement module.
    case 'help.page.owp_employee_engagement':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module created to manage employee engagement based on rewards') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function owp_employee_engagement_theme() {
  return [
    'list_stars' => [
      'template' => 'owp-employee-engagement',
      'render element' => 'children',
      'variables' => [],
    ],
    'add_star' => [
      'template' => 'block/block-add-stars-employees',
      'render element' => 'children',
      'variables' => [
        'listUsers' => [],
        'listTypes' => [],
      ],
    ],
  ];
}
