<?php

/**
 * @file
 * Contains connectorg_birthdays.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 * @param $route_name
 * @param RouteMatchInterface $route_match
 * @return string
 */
function connectorg_birthdays_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the connectorg_birthdays module.
    case 'help.page.connectorg_birthdays':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a block to show birthdays') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function connectorg_birthdays_theme()
{
  return [
    'todays_birthdays' => [
      'template' => 'block/block-todays-birthdays',
      'render element' => 'children',
      'variables' => [
        'list' => [],
        'header' => NULL
      ],
    ],
  ];
}
