<?php

/**
 * @file
 * Contains connectorg_news.module.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function connectorg_news_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the connectorg_news module.
    case 'help.page.connectorg_news':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('News Intranet') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function connectorg_news_theme($existing, $type, $theme, $path) {
  return [
    'news_entity' => [
      'path' => $path . '/templates',
      'template' => 'news-entity',
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function connectorg_news_theme_suggestions_news_entity(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  $suggestions[] = 'news_entity__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function connectorg_news_preprocess_news_entity(&$variables) {
  $variables['content'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  $entity = $variables['elements']['#news_entity'];
  $variables['author_name'] = \Drupal::service('renderer')
    ->render($variables['elements']['user_id']);
  $variables['url'] = $entity->toUrl()->toString();
}
