<?php

/**
 * @file
 * Contains connectorg_employee_engagement.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 * @param $route_name
 * @param RouteMatchInterface $route_match
 * @return string
 */
function connectorg_employee_engagement_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the connectorg_employee_engagement module.
    case 'help.page.connectorg_employee_engagement':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module created to manage employee engagement based on rewards') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function connectorg_employee_engagement_theme()
{
  return [
    'random_stars' => [
      'template' => 'block/block-random-employees-stars',
      'render element' => 'children',
      'variables' => [
        'listStars' => []
      ],
    ],
    'list_stars' => [
      'template' => 'block/block-employees-stars',
      'render element' => 'children',
      'variables' => [
        'listStars' => []
      ],
    ],
    'ranking' => [
      'template' => 'block/block-ranking-stars-employees',
      'render element' => 'children',
      'variables' => [
        'listUsers' => []
      ],
    ],
    'add_star' => [
      'template' => 'block/block-add-stars-employees',
      'render element' => 'children',
      'variables' => [
        'listUsers' => [],
        'listTypes' => [],
      ],
    ],
  ];
}
