<?php

/**
 * @file
 * Contains owp_microsites.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function owp_microsites_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the owp_microsites module.
    case 'help.page.owp_microsites':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to manage microsites') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function owp_microsites_theme() {
  return [
    'owp_microsites' => [
      'render element' => 'children',
    ],
  ];
}
