<?php

/**
 * @file
 * Contains owp_news.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function owp_news_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the owp_news module.
    case 'help.page.owp_news':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to handle news in an intranet') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function owp_news_theme() {
  return [
    'owp_news' => [
      'render element' => 'children',
    ],
  ];
}
